---
name: Build the container image

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  podman:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "arm64", "ppc64le", "s390x"]

    runs-on: ubuntu-22.04
    name: Build the containers with buildah
    steps:
      - uses: actions/checkout@v3
      - name: update buildah
        run: |
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$VERSION_ID/ /" | sudo tee /etc/apt/sources.list.d/openSUSE:Tools.list
          curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$VERSION_ID/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/libcontainers_unstable.gpg > /dev/null
          sudo apt update
          sudo apt install buildah

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - run: buildah bud --platform linux/${{ matrix.arch }} --layers .

  docker:
    runs-on: ubuntu-latest
    name: Build and publish the container with docker
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/') }}
          target: deploy
          tags: |
            ghcr.io/dcermak/container-layer-sizes:latest

      - name: Build and push the backend
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/') }}
          target: storage-backend-deploy
          tags: |
            ghcr.io/dcermak/container-layer-sizes-backend:latest
